### ISSUE TITLE
Bugs and Runtime Errors

### ISSUE THREAD

**Issue by tonyswink** [RichardWithAq/ToDoList#1]
- [x] Check if 'todolist.txt' exists [os.path.exists]
- [x] Exists = Continue
- [x] Doesn't Exist = Create it ('w')
- [x] Strip() whitespace from adding items to the todolist
- [x] Resolve the ValueError when removing items from the list (with a list)

**Comment by RichardWithAq** [comment]
Fixed all issues to the best of my abilities.
